name: Production Deployment

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"
      - "![0-9]*.[0-9]*.[0-9]*-*"

permissions:
  contents: read

jobs:
  deploy-production:
    name: Deploy Production
    uses: ./.github/workflows/deploy-pages.yml
    with:
      branch: main
      commit_hash: ${{ github.sha }}
      commit_message: Release ${{ github.ref_name }}
    secrets:
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
